
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
#
LD_LIBRARY_PATH=/usr/local/lib
export LD_LIBRARY_PATH

#export KEYTIMEOUT=50

# Color (needed for tmux)
export TERM=screen-256color-bce

# added by Anaconda 2.2.0 installer
export PATH="/home/john/anaconda3/bin:$PATH"

bindkey -v
bindkey -M viins 'jj' vi-cmd-mode
bindkey '^R' history-incremental-search-backward

alias jp='jupyter-notebook'

